// TEMPORARY CONTRACT: hand-written until the backend publishes openapi/openapi.json.
// When the spec-sync PR arrives, replace these types with the generated ones and update
// the paths below. Nothing outside src/services/ and src/mocks/ should need to change.
import { ApiError, apiFetch } from "./apiClient";

export const USER_TYPES = ["government", "forestry", "nature"] as const;
export type UserType = (typeof USER_TYPES)[number];

export interface DirectoryUser {
  userIdentifier: string;
  firstName: string;
  surname: string;
  email: string;
  managerXNumber: string;
  jobTitle: string;
}

export interface ProvisioningRequest {
  userType: UserType;
  userIdentifier: string;
  firstName: string;
  surname: string;
  email: string;
  managerXNumber: string;
  jobTitle: string;
  location: string;
  /** The JSM/Jira ticket is mandatory on every transaction. */
  jiraTicketId: string;
}

export interface ProvisioningRequestCreated {
  /** Generated by the backend for each transaction. It is never the JSM/Jira ticket. */
  transactionId: string;
}

export type UserLookupResult = { found: true; user: DirectoryUser } | { found: false };

export const userLookupPath = "/users/:userIdentifier";
export const provisioningRequestsPath = "/provisioning-requests";
export const locationsPath = "/locations";

export async function getLocations(): Promise<string[]> {
  const response = await apiFetch(locationsPath);
  if (!response.ok) {
    throw new ApiError(response.status);
  }
  const body: unknown = await response.json();
  if (!Array.isArray(body) || !body.every((item) => typeof item === "string")) {
    throw new Error("Unexpected locations response");
  }
  return body;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function readString(value: Record<string, unknown>, key: string): string {
  const field = value[key];
  return typeof field === "string" ? field : "";
}

function toDirectoryUser(value: unknown): DirectoryUser {
  if (!isRecord(value)) {
    throw new Error("Unexpected user lookup response");
  }
  return {
    userIdentifier: readString(value, "userIdentifier"),
    firstName: readString(value, "firstName"),
    surname: readString(value, "surname"),
    email: readString(value, "email"),
    managerXNumber: readString(value, "managerXNumber"),
    jobTitle: readString(value, "jobTitle"),
  };
}

export async function lookUpUser(userType: UserType, userIdentifier: string): Promise<UserLookupResult> {
  const query = new URLSearchParams({ userType });
  const response = await apiFetch(`/users/${encodeURIComponent(userIdentifier)}?${query.toString()}`);
  if (response.status === 404) {
    return { found: false };
  }
  if (!response.ok) {
    throw new ApiError(response.status);
  }
  return { found: true, user: toDirectoryUser(await response.json()) };
}

export async function submitProvisioningRequest(
  request: ProvisioningRequest,
): Promise<ProvisioningRequestCreated> {
  const response = await apiFetch(provisioningRequestsPath, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(request),
  });
  if (!response.ok) {
    throw new ApiError(response.status);
  }
  const body: unknown = await response.json();
  if (!isRecord(body) || typeof body.transactionId !== "string") {
    throw new Error("Unexpected provisioning response");
  }
  return { transactionId: body.transactionId };
}
